---
name: Install GitHub Release binary
description: Install a binary from a GitHub Release
author: Eric Crosson
branding:
  icon: arrow-down
  color: green

inputs:
  targets:
    description: Whitespace separated list of target GitHub Releases in format {owner}/{repository}@{tag}
    required: true
  token:
    description: GitHub access token or a Personal Access Token with 'repo' scope
    default: ${{ github.token }}
  cache:
    description: Runtime switch to enable/disable caching because GitHub is debugging issues in their caching API
    default: false
  ignore-existing-binary:
    description: Skip download if the binary already exists at the destination
    default: false

runs:
  using: node20
  main: dist/index.js
